import { GoogleGenerativeAI } from '@google/generative-ai';
import Anthropic from '@anthropic-ai/sdk';
import OpenAI from 'openai';
import { HfInference } from '@huggingface/inference';
import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import readline from 'readline';
import os from 'os';

// ──────────────────────────────────────────────
//  PROVIDER REGISTRY
// ──────────────────────────────────────────────

export const PROVIDERS = {
  gemini: {
    name: 'Google Gemini',
    envKey: 'GEMINI_API_KEY',
    defaultModel: 'gemini-2.0-flash',
    models: [
      'gemini-2.0-flash',
      'gemini-2.0-flash-lite',
      'gemini-1.5-flash',
      'gemini-1.5-flash-8b',
    ],
    keyUrl: 'https://aistudio.google.com/app/apikey',
  },
  openai: {
    name: 'OpenAI',
    envKey: 'OPENAI_API_KEY',
    defaultModel: 'gpt-4.1',
    models: [
      'gpt-4.1',
      'gpt-4.1-mini',
      'gpt-4.1-nano',
      'gpt-4o',
      'gpt-4o-mini',
      'o3',
      'o4-mini',
      'o3-mini',
    ],
    keyUrl: 'https://platform.openai.com/api-keys',
  },
  anthropic: {
    name: 'Anthropic Claude',
    envKey: 'ANTHROPIC_API_KEY',
    defaultModel: 'claude-3-5-sonnet-latest',
    models: [
      'claude-3-7-sonnet-20250219',
      'claude-3-5-sonnet-latest', 
      'claude-3-5-haiku-latest', 
      'claude-3-opus-latest'
    ],
    keyUrl: 'https://console.anthropic.com/settings/keys',
  },
  huggingface: {
    name: 'Hugging Face',
    envKey: 'HF_API_KEY',
    defaultModel: 'Qwen/Qwen2.5-72B-Instruct',
    models: [
      'Qwen/Qwen2.5-72B-Instruct',
      'meta-llama/Llama-3.3-70B-Instruct',
      'deepseek-ai/DeepSeek-R1',
      'speakleash/Bielik-11B-v2',
      'speakleash/Bielik-11B-v3.0-Instruct'
    ],
    keyUrl: 'https://huggingface.co/settings/tokens',
  },
  vertex: {
    name: 'Google Vertex AI',
    envKey: 'VERTEX_PROJECT_ID',
    defaultModel: 'gemini-2.5-pro-exp-03-25',
    models: [
      'gemini-2.5-pro-exp-03-25',
      'gemini-2.0-pro-exp',
      'gemini-1.5-pro',
      'gemini-1.5-flash',
      'gemini-2.0-flash',
    ],
    keyUrl: 'https://console.cloud.google.com/apis/credentials',
    configType: 'vertex',
  },
  local: {
    name: 'Local / SGLang (OpenAI-compatible)',
    envKey: 'LOCAL_API_KEY',
    defaultModel: 'speakleash/Bielik-11B-v3.0-Instruct',
    models: ['speakleash/Bielik-11B-v3.0-Instruct', 'custom-model'],
    keyUrl: 'http://localhost:30000/v1',
  },
};

// Active provider state
let activeProvider = null;   // 'gemini' | 'openai' | 'anthropic' | 'huggingface'
let activeClient = null;
let activeModel = null;
let conversationMessages = []; // universal message buffer
let systemPromptCache = '';

// ──────────────────────────────────────────────
//  SECURE KEYSTORE  (per-provider, encrypted)
// ──────────────────────────────────────────────

const KEYSTORE_NAME = '.babok_keystore';

function deriveSecret() {
  const material = `babok::${os.hostname()}::${os.userInfo().username}::${process.cwd()}`;
  return crypto.createHash('sha256').update(material).digest();
}

function xorCipher(buf, key) {
  const out = Buffer.alloc(buf.length);
  for (let i = 0; i < buf.length; i++) out[i] = buf[i] ^ key[i % key.length];
  return out;
}

function getKeystorePath() {
  return path.join(process.cwd(), KEYSTORE_NAME);
}

function readKeystore() {
  const ksPath = getKeystorePath();
  if (!fs.existsSync(ksPath)) return {};
  try {
    return JSON.parse(fs.readFileSync(ksPath, 'utf-8'));
  } catch { return {}; }
}

function writeKeystore(data) {
  data._WARNING = 'Auto-generated by BABOK CLI. Do NOT commit to git.';
  data.updated_at = new Date().toISOString();
  fs.writeFileSync(getKeystorePath(), JSON.stringify(data, null, 2), 'utf-8');
}

/**
 * Read stored API key for a specific provider.
 */
export function readStoredKey(provider) {
  const ks = readKeystore();
  const entry = ks[provider];
  if (!entry?.k) return null;
  try {
    const encrypted = Buffer.from(entry.k, 'base64');
    const decrypted = xorCipher(encrypted, deriveSecret()).toString('utf-8');
    if (decrypted.length < 8) return null;
    // Vertex AI config is stored as JSON — skip alphanumeric-only check
    if (provider === 'vertex') return decrypted;
    if (/^[A-Za-z0-9_\-:.]+$/.test(decrypted)) return decrypted;
    return null;
  } catch { return null; }
}

/**
 * Store API key for a specific provider (encrypted).
 */
export function storeKey(provider, apiKey) {
  const ks = readKeystore();
  ks[provider] = {
    k: xorCipher(Buffer.from(apiKey, 'utf-8'), deriveSecret()).toString('base64'),
    stored_at: new Date().toISOString(),
  };
  writeKeystore(ks);
}

/**
 * Remove stored key for a provider (or all).
 */
export function clearStoredKey(provider) {
  if (!provider) {
    const ksPath = getKeystorePath();
    if (fs.existsSync(ksPath)) fs.unlinkSync(ksPath);
    return;
  }
  const ks = readKeystore();
  delete ks[provider];
  writeKeystore(ks);
}

/**
 * List providers that have stored keys.
 */
export function listStoredProviders() {
  const ks = readKeystore();
  return Object.keys(PROVIDERS).filter(p => ks[p]?.k);
}

// ──────────────────────────────────────────────
//  API KEY RESOLUTION  (env → .env → keystore)
// ──────────────────────────────────────────────

/**
 * Get API key for a provider without prompting.
 */
export function getApiKey(provider) {
  const info = PROVIDERS[provider];
  if (!info) return null;

  // Vertex AI: compose config from env vars instead of a single API key
  if (provider === 'vertex') {
    const projectId = process.env.VERTEX_PROJECT_ID;
    if (projectId) {
      const cfg = {
        project_id: projectId,
        location: process.env.VERTEX_LOCATION || 'us-central1',
      };
      if (process.env.GOOGLE_APPLICATION_CREDENTIALS) {
        cfg.credentials_file = process.env.GOOGLE_APPLICATION_CREDENTIALS;
      }
      return JSON.stringify(cfg);
    }
    return readStoredKey('vertex');
  }

  // 1. Environment variable
  if (process.env[info.envKey]) return process.env[info.envKey];

  // 2. .env file (gitignored)
  const envPath = path.join(process.cwd(), '.env');
  if (fs.existsSync(envPath)) {
    const content = fs.readFileSync(envPath, 'utf-8');
    const match = content.match(new RegExp(`^${info.envKey}\\s*=\\s*(.+)$`, 'm'));
    if (match?.[1]?.trim()) return match[1].trim().replace(/^["']|["']$/g, '');
  }

  // 3. Encrypted keystore
  return readStoredKey(provider);
}

/**
 * Interactively select provider, model and enter API key.
 * Returns { provider, apiKey, model }
 */
export async function promptForProvider() {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  const ask = (q) => new Promise(resolve => rl.question(q, a => resolve(a.trim())));

  try {
    const stored = listStoredProviders();
    const providerList = Object.entries(PROVIDERS);

    // ── Krok 1: Wybor dostawcy ──
    process.stdout.write('\n');
    process.stdout.write('  Wybierz dostawce AI:\n\n');
    providerList.forEach(([key, info], i) => {
      const badge = stored.includes(key) ? chalk_green('  [klucz zapisany]') : '';
      process.stdout.write(`    ${i + 1}. ${info.name}${badge}\n`);
    });
    process.stdout.write('\n');

    const provNum = await ask(`  Numer dostawcy (1-${providerList.length}): `);
    const provIdx = parseInt(provNum) - 1;
    if (isNaN(provIdx) || provIdx < 0 || provIdx >= providerList.length) {
      throw new Error('Nieprawidlowy numer dostawcy.');
    }
    const [providerKey, info] = providerList[provIdx];

    // ── Krok 2: Wybor modelu ──
    process.stdout.write('\n');
    process.stdout.write(`  Modele ${info.name}:\n\n`);
    info.models.forEach((m, i) => {
      const def = m === info.defaultModel ? chalk_green('  <domyslny>') : '';
      process.stdout.write(`    ${i + 1}. ${m}${def}\n`);
    });
    process.stdout.write('\n');

    const modelNum = await ask('  Numer modelu [1]: ');
    const modelIdx = modelNum === '' ? 0 : parseInt(modelNum) - 1;
    const selectedModel = info.models[modelIdx >= 0 && modelIdx < info.models.length ? modelIdx : 0];

    // ── Krok 3: Klucz API ──
    let apiKey = getApiKey(providerKey);
    if (apiKey) {
      const ans = await ask(`  Uzyc zapisanego klucza ${info.name}? (T/n): `);
      if (ans.toLowerCase().startsWith('n')) {
        apiKey = await _askForKeyAsync(ask, providerKey, info);
      }
    } else {
      apiKey = await _askForKeyAsync(ask, providerKey, info);
    }

    rl.close();
    return { provider: providerKey, apiKey, model: selectedModel };

  } catch (err) {
    rl.close();
    throw err;
  }
}

async function _askForKeyAsync(ask, providerKey, info) {
  if (providerKey === 'vertex') {
    return _collectVertexConfig(ask);
  }

  process.stdout.write('\n');
  process.stdout.write(`  Klucz API wymagany dla: ${info.name}\n`);
  process.stdout.write(`  Pobierz na: ${info.keyUrl}\n\n`);
  process.stdout.write('  Klucz jest przechowywany tylko lokalnie (zaszyfrowany, gitignored).\n\n');

  const key = await ask('  Podaj klucz API: ');
  if (!key) throw new Error('Nie podano klucza API.');

  const saveAns = await ask('  Zapisac na przyszlosc? (T/n): ');
  if (!saveAns.toLowerCase().startsWith('n')) {
    storeKey(providerKey, key);
    process.stdout.write('  Klucz zapisany (.babok_keystore, zaszyfrowany, gitignored)\n\n');
  } else {
    process.stdout.write('  Klucz uzywany tylko w tej sesji (nie zapisano)\n\n');
  }
  return key;
}

async function _collectVertexConfig(ask) {
  process.stdout.write('\n');
  process.stdout.write('  Konfiguracja Google Vertex AI\n');
  process.stdout.write('  ─────────────────────────────────────────────────────\n');
  process.stdout.write('  Wymagane: Google Cloud Project ID\n');
  process.stdout.write('  Uwierzytelnianie: Service Account JSON  lub  ADC\n');
  process.stdout.write('  ADC: uruchom "gcloud auth application-default login"\n\n');

  const projectId = await ask('  Google Cloud Project ID: ');
  if (!projectId) throw new Error('Project ID jest wymagany dla Vertex AI.');

  const locRaw = await ask('  Region [us-central1]: ');
  const location = locRaw || 'us-central1';

  process.stdout.write('\n');
  process.stdout.write('  Sciezka do pliku klucza Service Account JSON\n');
  process.stdout.write('  (Enter = uzyj ADC, np. po "gcloud auth application-default login")\n\n');
  const credFile = await ask('  Plik klucza SA (opcjonalnie): ');

  const config = { project_id: projectId, location };
  if (credFile) config.credentials_file = credFile;
  const configStr = JSON.stringify(config);

  const saveAns = await ask('  Zapisac konfiguracje na przyszlosc? (T/n): ');
  if (!saveAns.toLowerCase().startsWith('n')) {
    storeKey('vertex', configStr);
    process.stdout.write('  Konfiguracja zapisana (.babok_keystore, gitignored)\n\n');
  } else {
    process.stdout.write('  Konfiguracja uzywana tylko w tej sesji (nie zapisano)\n\n');
  }
  return configStr;
}

// Legacy callback-based helper — used only by promptForKeyOnly()
function askForKey(rl, providerKey, info, resolve, reject) {
  process.stdout.write('\n');
  process.stdout.write(`  Klucz API wymagany dla: ${info.name}\n`);
  process.stdout.write(`  Pobierz na: ${info.keyUrl}\n\n`);
  process.stdout.write('  Klucz jest przechowywany tylko lokalnie (zaszyfrowany, gitignored).\n\n');

  rl.question('  Podaj klucz API: ', (apiKey) => {
    const key = apiKey.trim();
    if (!key) { rl.close(); reject(new Error('Nie podano klucza API.')); return; }

    rl.question('  Zapisac na przyszlosc? (T/n): ', (ans) => {
      rl.close();
      if (!ans.trim() || !ans.trim().toLowerCase().startsWith('n')) {
        storeKey(providerKey, key);
        process.stdout.write('  Klucz zapisany (.babok_keystore, zaszyfrowany, gitignored)\n\n');
      } else {
        process.stdout.write('  Klucz uzywany tylko w tej sesji (nie zapisano)\n\n');
      }
      resolve({ provider: providerKey, apiKey: key });
    });
  });
}

/**
 * Interactively ask for an API key for a specific provider.
 */
export function promptForKeyOnly(providerKey, rl) {
  const info = PROVIDERS[providerKey];
  return new Promise((resolve, reject) => {
    askForKey(rl, providerKey, info, resolve, reject);
  });
}

// simple green text without chalk dependency in this module
function chalk_green(s) { return `\x1b[32m${s}\x1b[0m`; }

// ──────────────────────────────────────────────
//  UNIFIED CLIENT INIT & CHAT
// ──────────────────────────────────────────────

/**
 * Initialize the selected provider.
 */
export async function initializeProvider(provider, apiKey, modelName) {
  const info = PROVIDERS[provider];
  if (!info) throw new Error(`Unknown provider: ${provider}`);
  const model = modelName || info.defaultModel;

  switch (provider) {
    case 'gemini': {
      const genAI = new GoogleGenerativeAI(apiKey);
      activeClient = genAI.getGenerativeModel({ model });
      break;
    }
    case 'vertex': {
      const { VertexAI } = await import('@google-cloud/vertexai');
      let cfg = {};
      try { cfg = JSON.parse(apiKey); } catch { cfg = { project_id: apiKey }; }
      const vertexOptions = {
        project: cfg.project_id,
        location: cfg.location || 'us-central1',
      };
      if (cfg.credentials_file) {
        vertexOptions.googleAuthOptions = { keyFilename: cfg.credentials_file };
      }
      const vertexAI = new VertexAI(vertexOptions);
      activeClient = vertexAI.getGenerativeModel({ model });
      break;
    }
    case 'openai': {
      activeClient = new OpenAI({ apiKey });
      break;
    }
    case 'local': {
      // For local servers like SGLang, Ollama (OpenAI API), vLLM
      // We check if modelName is actually a URL, or use a default local URL
      const baseURL = modelName?.startsWith('http') ? modelName : 'http://localhost:30000/v1';
      activeClient = new OpenAI({
        apiKey: apiKey || 'not-needed',
        baseURL: baseURL
      });
      activeProvider = 'openai'; // Reuse OpenAI logic for sendMessageStream
      activeModel = modelName || info.defaultModel;
      return;
    }
    case 'anthropic': {
      activeClient = new Anthropic({ apiKey });
      break;
    }
    case 'huggingface': {
      activeClient = new HfInference(apiKey);
      break;
    }
  }

  activeProvider = provider;
  activeModel = model;
}

/**
 * Create a stateless, reusable LLM client without touching global state.
 * Each chat() call is a single-turn, non-streaming request.
 * Use in the orchestrator pipeline for per-stage model routing.
 *
 * @param {string} provider
 * @param {string} apiKey
 * @param {string} [modelName]
 * @returns {{ chat: (systemPrompt: string, userMessage: string) => Promise<string>, providerName: string, modelName: string }}
 */
export function createLlmClient(provider, apiKey, modelName) {
  const info = PROVIDERS[provider];
  if (!info) throw new Error(`createLlmClient: unknown provider "${provider}"`);
  const model = modelName || info.defaultModel;

  const chat = async (systemPrompt, userMessage) => {
    switch (provider) {
      case 'gemini': {
        const genAI = new GoogleGenerativeAI(apiKey);
        const genModel = genAI.getGenerativeModel({
          model,
          systemInstruction: systemPrompt,
          generationConfig: { maxOutputTokens: 8192, temperature: 0.7 },
        });
        const result = await genModel.generateContent(userMessage);
        return result.response.text();
      }
      case 'vertex': {
        const { VertexAI } = await import('@google-cloud/vertexai');
        let cfg = {};
        try { cfg = JSON.parse(apiKey); } catch { cfg = { project_id: apiKey }; }
        const vertexOptions = {
          project: cfg.project_id,
          location: cfg.location || 'us-central1',
        };
        if (cfg.credentials_file) {
          vertexOptions.googleAuthOptions = { keyFilename: cfg.credentials_file };
        }
        const vertexAI = new VertexAI(vertexOptions);
        const genModel = vertexAI.getGenerativeModel({ model });
        const result = await genModel.generateContent({
          contents: [{ role: 'user', parts: [{ text: userMessage }] }],
          systemInstruction: { parts: [{ text: systemPrompt }] },
        });
        return result.response.candidates?.[0]?.content?.parts?.[0]?.text || '';
      }
      case 'openai':
      case 'local': {
        const baseURL = provider === 'local'
          ? (model?.startsWith('http') ? model : 'http://localhost:30000/v1')
          : undefined;
        const client = new OpenAI({ apiKey: apiKey || 'not-needed', ...(baseURL ? { baseURL } : {}) });
        const resp = await client.chat.completions.create({
          model: provider === 'local' ? info.defaultModel : model,
          messages: [
            { role: 'system', content: systemPrompt },
            { role: 'user', content: userMessage },
          ],
          max_tokens: 8192,
          temperature: 0.7,
        });
        return resp.choices?.[0]?.message?.content || '';
      }
      case 'anthropic': {
        const client = new Anthropic({ apiKey });
        const resp = await client.messages.create({
          model,
          system: systemPrompt,
          messages: [{ role: 'user', content: userMessage }],
          max_tokens: 8192,
        });
        return resp.content?.[0]?.text || '';
      }
      case 'huggingface': {
        const hf = new HfInference(apiKey);
        const resp = await hf.chatCompletion({
          model,
          messages: [
            { role: 'system', content: systemPrompt },
            { role: 'user', content: userMessage },
          ],
          max_tokens: 8192,
        });
        return resp.choices?.[0]?.message?.content || '';
      }
      default:
        throw new Error(`createLlmClient: unsupported provider "${provider}"`);
    }
  };

  return { chat, providerName: info.name, modelName: model };
}

/**
 * Start chat session (sets system prompt, optionally loads history).
 */
export function startChatSession(systemPrompt, history = []) {
  systemPromptCache = systemPrompt;
  conversationMessages = [...history];
}

/**
 * Clear current conversation history in memory.
 */
export function clearChatHistory() {
  conversationMessages = [];
}

/**
 * Send message and stream response (provider-agnostic).
 */
export async function sendMessageStream(message, onChunk) {
  conversationMessages.push({ role: 'user', parts: [{ text: message }] });

  let fullResponse = '';

  switch (activeProvider) {
    case 'gemini': {
      const chat = activeClient.startChat({
        history: conversationMessages.slice(0, -1),
        systemInstruction: { parts: [{ text: systemPromptCache }] },
        generationConfig: { maxOutputTokens: 8192, temperature: 0.7 },
      });
      const result = await chat.sendMessageStream(message);
      for await (const chunk of result.stream) {
        const text = chunk.text();
        fullResponse += text;
        if (onChunk) onChunk(text);
      }
      break;
    }

    case 'vertex': {
      // Vertex AI SDK — same startChat API but chunk.text() not available;
      // extract text from candidates array instead.
      const chat = activeClient.startChat({
        history: conversationMessages.slice(0, -1).map(m => ({
          role: m.role === 'model' ? 'model' : 'user',
          parts: m.parts,
        })),
        systemInstruction: { parts: [{ text: systemPromptCache }] },
        generationConfig: { maxOutputTokens: 8192, temperature: 0.7 },
      });
      const result = await chat.sendMessageStream(message);
      for await (const chunk of result.stream) {
        const text = chunk.candidates?.[0]?.content?.parts?.[0]?.text || '';
        fullResponse += text;
        if (onChunk && text) onChunk(text);
      }
      break;
    }

    case 'openai': {
      const messages = [
        { role: 'system', content: systemPromptCache },
        ...conversationMessages.map(m => ({
          role: m.role === 'model' ? 'assistant' : m.role,
          content: m.parts[0].text,
        })),
      ];
      const stream = await activeClient.chat.completions.create({
        model: activeModel,
        messages,
        stream: true,
        max_tokens: 8192,
        temperature: 0.7,
      });
      for await (const chunk of stream) {
        const text = chunk.choices?.[0]?.delta?.content || '';
        fullResponse += text;
        if (onChunk && text) onChunk(text);
      }
      break;
    }

    case 'anthropic': {
      const messages = conversationMessages.map(m => ({
        role: m.role === 'model' ? 'assistant' : m.role,
        content: m.parts[0].text,
      }));
      const stream = activeClient.messages.stream({
        model: activeModel,
        system: systemPromptCache,
        messages,
        max_tokens: 8192,
        temperature: 0.7,
      });
      for await (const event of stream) {
        if (event.type === 'content_block_delta' && event.delta?.text) {
          fullResponse += event.delta.text;
          if (onChunk) onChunk(event.delta.text);
        }
      }
      break;
    }

    case 'huggingface': {
      const messages = [
        { role: 'system', content: systemPromptCache },
        ...conversationMessages.map(m => ({
          role: m.role === 'model' ? 'assistant' : m.role,
          content: m.parts[0].text,
        })),
      ];
      
      // Better detection for direct endpoint URLs
      const isEndpoint = activeModel.startsWith('http') || activeModel.includes('.endpoints.huggingface.cloud');
      
      const options = {
        messages,
        max_tokens: 8192,
        temperature: 0.7,
        provider: 'auto',
      };

      // When using a dedicated endpoint, we SHOULD NOT pass the 'model' property
      if (!isEndpoint) {
        options.model = activeModel;
      }

      const client = isEndpoint ? activeClient.endpoint(activeModel) : activeClient;
      const stream = client.chatCompletionStream(options);

      for await (const chunk of stream) {
        const text = chunk.choices?.[0]?.delta?.content || '';
        fullResponse += text;
        if (onChunk && text) onChunk(text);
      }
      break;
    }

    default:
      throw new Error(`Provider ${activeProvider} not initialized`);
  }

  conversationMessages.push({ role: 'model', parts: [{ text: fullResponse }] });
  return fullResponse;
}

/**
 * Get active provider info for display.
 */
export function getActiveProviderInfo() {
  return {
    provider: activeProvider,
    model: activeModel,
    name: PROVIDERS[activeProvider]?.name || activeProvider,
  };
}

// ──────────────────────────────────────────────
//  PROMPT LOADING
// ──────────────────────────────────────────────

export function loadStagePrompt(stageNumber) {
  const possiblePaths = [
    path.join(process.cwd(), 'BABOK_AGENT', 'stages', `BABOK_agent_stage_${stageNumber}.md`),
    path.join(process.cwd(), 'BABOK_AGENT', 'BABOK_Agent_System_Prompt.md'),
  ];
  for (const p of possiblePaths) {
    if (fs.existsSync(p)) return fs.readFileSync(p, 'utf-8');
  }
  return getGenericStagePrompt(stageNumber);
}

export function loadMainSystemPrompt() {
  const possiblePaths = [
    path.join(process.cwd(), 'BABOK_AGENT', 'BABOK_Agent_System_Prompt.md'),
    path.join(process.cwd(), 'BABOK_AGENT_SYSTEM_PROMPT.md'),
  ];
  for (const p of possiblePaths) {
    if (fs.existsSync(p)) return fs.readFileSync(p, 'utf-8');
  }
  return '';
}

function getGenericStagePrompt(stageNumber) {
  const stageNames = {
    1: 'Project Initialization & Stakeholder Mapping',
    2: 'Current State Analysis (AS-IS)',
    3: 'Problem Domain Analysis',
    4: 'Solution Requirements Definition',
    5: 'Future State Design (TO-BE)',
    6: 'Gap Analysis & Implementation Roadmap',
    7: 'Risk Assessment & Mitigation Strategy',
    8: 'Business Case & ROI Model',
  };
  return `You are BABOK Agent, an expert Business Analyst specializing in IT projects.

Currently working on: Stage ${stageNumber} - ${stageNames[stageNumber]}

Guidelines:
- Ask clarifying questions when needed
- Provide evidence-based analysis
- Wait for human validation before proceeding to deliverables
- Use Polish language for responses when user writes in Polish
- Follow BABOK v3 methodology`;
}
